### ISSUE TITLE
DRM tegra DMA API / SMMU problems with kernel-5.5-rc6 on smaug

### ISSUE THREAD

**Issue by denysvitali** [pixelc-linux/linux#1]
Apparently since 5.4.12 there has been a breaking change that has led to a problem with the DRM / GPU. Specifically, it is not possible to get a display output with smaug-5.5-rc6.  
  
Ping @thierryreding since he worked on some of the patches for Tegra that have been merged to upstream.

#### Denys
```
[    2.329487] [drm] Initialized nouveau 1.3.1 20120801 for 57000000.gpu on minor 0
[    2.338112] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[    2.344732] [drm] No driver support for vblank timestamp query.
[    2.350723] drm drm: failed to allocate buffer of size 18432000
[    2.356647] drm drm: failed to set initial configuration: -12
[    2.362533] drm: probe of drm failed with error -12
```

#### Vartom
``` 
[    4.507691] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[    4.514326] [drm] No driver support for vblank timestamp query.
[    4.520363] drm drm: failed to allocate buffer of size 18432000
[    4.526299] drm drm: failed to set initial configuration: -12
[    4.532563] drm: probe of drm failed with error -12
```

@vartom  is having the exact same problems. We're discussing it on https://t.me/pixelc-linux

**Comment by vartom** [comment]
This is clearly a problem with the SMMU. I checked on 5.4.12 if I turned off the SMMU
# CONFIG_TEGRA_IOMMU_SMMU is not set
# CONFIG_ARM_SMMU is not set
# CONFIG_ARM_SMMU_V3 is not set
 then I get the same error. 

[kout5412drmsmmu2.txt](https://github.com/pixelc-linux/linux/files/4092309/kout5412drmsmmu2.txt)
[kout5412drmNosmmu1.txt](https://github.com/pixelc-linux/linux/files/4092310/kout5412drmNosmmu1.txt)

**Comment by vartom** [comment]
Fix 
CONFIG_CMA_SIZE_MBYTES=128
